FROM golang:1.18

ENV VERSION v1.0.36
ENV GOCACHE /tmp
WORKDIR /go/src/github/mlabouardy/movies-parser

RUN wget  https://github.com/sonatype-nexus-community/nancy/releases/download/v1.0.36/nancy_1.0.36_linux_amd64.deb -O nancy && \
    chmod +x nancy && mv nancy /usr/local/bin/nancy
RUN go install  golang.org/x/lint/golint@latest

COPY . .

RUN go get -v 
